[package]
name = "swarms-rs-rust-agent-fun"
version = "1.0.0"
authors = ["Diego.Pacheco"]
edition = "2024"

[dependencies]
tokio = { version = "1.36", features = ["full"] }
swarms-rs = "0.2.1"
dotenv = "0.15"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
env_logger = "0.11"
