[package]
name = "backend"
version = "0.1.0"
edition = "2024"
rust-version = "1.93"

[dependencies]
actix-web = "4"
actix-cors = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = "0.4"
